[
	{
		"key": "dbln",
		"value": "%7B%2261588401066782%22%3A%22JnxsXsMF%22%7D",
		"domain": "facebook.com",
		"path": "/login/device-based/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.319Z",
		"lastAccessed": "2026-02-28T03:01:04.323Z"
	},
	{
		"key": "datr",
		"value": "j1aiaWJyDPtNbH1LU6k3nWSD",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.323Z",
		"lastAccessed": "2026-02-28T03:01:04.323Z"
	},
	{
		"key": "sb",
		"value": "j1aiafcdrz7gMAhTO85b3gG3",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.323Z",
		"lastAccessed": "2026-02-28T03:01:04.323Z"
	},
	{
		"key": "c_user",
		"value": "61588401066782",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.323Z",
		"lastAccessed": "2026-02-28T03:01:04.323Z"
	},
	{
		"key": "xs",
		"value": "18%3AzCtpSbhUmcsrkg%3A2%3A1772246725%3A-1%3A-1",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.323Z",
		"lastAccessed": "2026-02-28T03:01:04.323Z"
	},
	{
		"key": "locale",
		"value": "en_GB",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.323Z",
		"lastAccessed": "2026-02-28T03:01:04.323Z"
	},
	{
		"key": "pas",
		"value": "61588401066782%3A6KtIEgzbCK",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.323Z",
		"lastAccessed": "2026-02-28T03:01:04.323Z"
	},
	{
		"key": "vpd",
		"value": "v1%3B653x336x3.2168333530426025",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.323Z",
		"lastAccessed": "2026-02-28T03:01:04.323Z"
	},
	{
		"key": "fr",
		"value": "0FjPFIHtRS9WGS6jr.AWdHFnKeGD1Ppc6c4QaVBVSBc2YP9tDnN5UBMwQgrn5BFrlfeuA.BpolaP..AAA.0.0.Bpoln1.AWfDgIGafeo94pVcOfWOsB61c_A",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.323Z",
		"lastAccessed": "2026-02-28T03:01:04.323Z"
	},
	{
		"key": "ps_l",
		"value": "1",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.323Z",
		"lastAccessed": "2026-02-28T03:01:04.324Z"
	},
	{
		"key": "ps_n",
		"value": "1",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.324Z",
		"lastAccessed": "2026-02-28T03:01:04.324Z"
	},
	{
		"key": "fbl_st",
		"value": "101620865%3BT%3A29537459",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.324Z",
		"lastAccessed": "2026-02-28T03:01:04.324Z"
	},
	{
		"key": "wl_cbv",
		"value": "v2%3Bclient_version%3A3100%3Btimestamp%3A1772247541",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-28T03:01:04.324Z",
		"lastAccessed": "2026-02-28T03:01:04.324Z"
	}
]
